# Generated by Django 4.2.9 on 2024-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_image',
            field=models.URLField(default='https://www.example.com'),
            preserve_default=False,
        ),
    ]
