# Generated by Django 4.2.9 on 2024-01-28 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beanapi', '0002_drink_drink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddrink',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beanapi.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereddrink',
            name='preference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beanapi.preference'),
            preserve_default=False,
        ),
    ]
