# Generated by Django 4.2.9 on 2024-01-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanapi', '0003_ordereddrink_order_ordereddrink_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
