# Generated by Django 4.2.9 on 2024-02-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanapi', '0004_order_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
